# Консервативная конфигурация для долгосрочного инвестирования

# Настройки данных
data:
  provider: yfinance
  symbols:
    - SBER
    - GAZP
    - LKOH
  update_interval: 3600   # 1 час - достаточно для долгосрочных инвестиций
  history_days: 730       # 2 года истории

# Настройки нейросетей
neural_networks:
  models:
    - name: deepseek_analyzer
      type: deepseek
      weight: 0.6
      enabled: true
      api_key: ${DEEPSEEK_API_KEY}
      base_url: "https://api.deepseek.com/v1"
      model_name: "deepseek-chat"
      max_tokens: 4000
      temperature: 0.2    # Более консервативные предсказания
      analysis_window: 60 # Больший период анализа
      feature_importance_threshold: 0.15
      
    - name: xgboost_classifier
      type: xgboost
      weight: 0.4
      enabled: true
      n_estimators: 300
      max_depth: 10
      learning_rate: 0.01
      subsample: 0.9
      colsample_bytree: 0.9
      buy_threshold: 0.1   # Более высокий порог для покупки
      sell_threshold: -0.1 # Более высокий порог для продажи
      
  analysis_interval: 7200  # 2 часа - для долгосрочного анализа
  ensemble_method: weighted_average

# Настройки торговли
trading:
  broker: paper
  signal_threshold: 0.75   # Высокий порог для консервативных сигналов
  signal_check_interval: 3600  # 1 час - редко проверяем сигналы
  max_positions: 5         # Меньше позиций
  position_size: 0.2       # 20% от капитала на позицию - крупные позиции
  min_trade_interval: 7200  # 2 часа между сделками по одному символу
  
  broker_settings:
    tinkoff:
      token: ${TINKOFF_TOKEN}
      sandbox: true
      account_id: null
    sber:
      token: "your_sber_token"
      sandbox: true

# Настройки портфеля
portfolio:
  initial_capital: 1000000
  max_risk_per_trade: 0.05  # 5% риска на сделку
  max_portfolio_risk: 0.2    # 20% максимальный риск портфеля
  update_interval: 3600      # 1 час
  rebalance_threshold: 0.1   # 10% отклонение для ребалансировки

# Настройки логирования
logging:
  level: INFO
  file: logs/investment_system.log
  max_size: 10 MB
  retention: 30 days
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"

# Настройки уведомлений
notifications:
  enabled: true
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "frolov.fff@yandex.ru"
    password: "Oleg1988.ge"
    to_email: "frolov.fff@yandex.ru"
  
  telegram:
    bot_token: "your_telegram_bot_token"
    chat_id: "your_chat_id"

# Настройки мониторинга
monitoring:
  enabled: true
  web_interface:
    enabled: true
    host: "localhost"
    port: 8080
  
  metrics:
    enabled: true
    export_interval: 3600  # 1 час
