# Тестовая конфигурация с минимальными интервалами для быстрого тестирования

# Настройки данных
data:
  provider: russian  # Используем российский провайдер для MOEX акций
  symbols:
    - SBER   # Сбербанк
    - GAZP   # Газпром
    - LKOH   # Лукойл
    - NVTK   # Новатэк
    - ROSN   # Роснефть
    - GMKN   # ГМК Норникель
    - YNDX   # Яндекс
    - MGNT   # Магнит
    - TATN   # Татнефть
    - SNGS   # Сургутнефтегаз
  update_interval: 180  # 3 минуты (180 секунд)
  history_days: 30      # Меньше истории для быстрой загрузки

# Настройки нейросетей
neural_networks:
  models:
    - name: deepseek_analyzer
      type: deepseek
      weight: 0.6
      enabled: true
      api_key: ${DEEPSEEK_API_KEY}
      base_url: "https://api.deepseek.com/v1"
      model_name: "deepseek-chat"
      max_tokens: 2000  # Меньше токенов для быстрого ответа
      temperature: 0.3
      analysis_window: 10  # Меньший период анализа
      feature_importance_threshold: 0.1
      
    - name: xgboost_classifier
      type: xgboost
      weight: 0.4
      enabled: true
      n_estimators: 50   # Меньше деревьев для быстрого обучения
      max_depth: 4       # Меньшая глубина
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      buy_threshold: 0.05
      sell_threshold: -0.05
      
  analysis_interval: 180  # 3 минуты (180 секунд)
  ensemble_method: weighted_average

# Настройки торговли
trading:
  broker: tinkoff  # Используем T-Bank песочницу!
  signal_threshold: 0.5   # Низкий порог для частых сигналов в тестах
  signal_check_interval: 180  # 3 минуты (180 секунд)
  max_positions: 10       # Больше позиций для разнообразия
  position_size: 0.10     # 10% от капитала на позицию
  min_trade_interval: 300  # 5 минут между сделками по одному символу
  
  broker_settings:
    tinkoff:
      token: ${TINKOFF_TOKEN}  # Из переменной окружения
      sandbox: true            # Использовать песочницу T-Bank
      account_id: "24fdd4b3-aba2-4410-ae91-d57a8190909b"  # Ваш sandbox счет (сохранен!)
      # Адрес API (автоматически выбирается в зависимости от sandbox)
      # sandbox: sandbox-invest-public-api.tbank.ru:443
      # production: invest-public-api.tbank.ru:443
      # 
      # ℹ️ Счета в песочнице хранятся 3 месяца с даты последнего использования
      # Если счет удалится - установите account_id: null для создания нового
    sber:
      token: "your_sber_token"
      sandbox: true

# Настройки портфеля
portfolio:
  initial_capital: 100000  # Меньший капитал для тестов
  max_risk_per_trade: 0.01  # 1% риска на сделку - консервативно
  max_portfolio_risk: 0.05   # 5% максимальный риск портфеля
  update_interval: 180       # 3 минуты (180 секунд)
  rebalance_threshold: 0.02  # 2% отклонение для ребалансировки

# Настройки логирования
logging:
  level: DEBUG  # Подробные логи для тестов
  file: logs/test_system.log
  max_size: 5 MB
  retention: 7 days
  format: "{time:HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"

# Настройки уведомлений
notifications:
  enabled: false  # Отключены для тестов
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "frolov.fff@yandex.ru"
    password: "Oleg1988.ge"
    to_email: "frolov.fff@yandex.ru"
  
  telegram:
    bot_token: "your_telegram_bot_token"
    chat_id: "your_chat_id"

# Настройки мониторинга
monitoring:
  enabled: true
  web_interface:
    enabled: false  # Отключен для тестов
    host: "localhost"
    port: 8080
  
  metrics:
    enabled: true
    export_interval: 180  # 3 минуты (180 секунд)
