# Конфигурация для опытных пользователей
# Более агрессивная настройка с оптимизированными параметрами

# Настройки данных
data:
  provider: yfinance
  symbols:
    - SBER                    # Сбербанк
    - GAZP                    # Газпром
    - LKOH                    # Лукойл
    - NVTK                    # НОВАТЭК
    - ROSN                    # Роснефть
    - NLMK                    # НЛМК
    - MAGN                    # ММК
    - YNDX                    # Яндекс
  update_interval: 300        # Обновление каждые 5 минут
  history_days: 730          # 2 года истории

# Настройки нейросетей (оптимизированные)
neural_networks:
  models:
    - name: lstm_advanced
      type: lstm
      weight: 0.4
      enabled: true
      sequence_length: 120    # Больше данных для анализа
      lstm_units: [100, 100, 50]  # Больше слоев и нейронов
      dropout_rate: 0.2
      learning_rate: 0.001
      batch_size: 32
      epochs: 150             # Больше эпох для лучшего обучения
      
    - name: xgb_advanced
      type: xgboost
      weight: 0.3
      enabled: true
      n_estimators: 300       # Больше деревьев
      max_depth: 8           # Больше глубина
      learning_rate: 0.05    # Оптимизированная скорость обучения
      subsample: 0.8
      colsample_bytree: 0.8
      buy_threshold: 0.04    # Более чувствительные пороги
      sell_threshold: -0.04
      
    - name: deepseek_advanced
      type: deepseek
      weight: 0.3
      enabled: true
      api_key: ${DEEPSEEK_API_KEY}
      model_name: "deepseek-chat"
      max_tokens: 6000        # Больше токенов для детального анализа
      temperature: 0.4        # Более творческие предсказания
      analysis_window: 60     # Больше данных для анализа
      
  analysis_interval: 300      # Анализ каждые 5 минут
  ensemble_method: confidence_weighted  # Более сложный метод ансамбля

# Настройки торговли (агрессивные)
trading:
  broker: paper               # Можно переключить на реального брокера
  signal_threshold: 0.6       # Средний порог уверенности
  signal_check_interval: 30   # Проверка сигналов каждые 30 секунд
  max_positions: 12           # Больше позиций
  position_size: 0.08         # 8% от капитала на позицию
  
  broker_settings:
    tinkoff:
      token: "your_tinkoff_token"
      sandbox: true           # Переключить на false для реальной торговли
    sber:
      token: "your_sber_token"
      sandbox: true

# Настройки портфеля (оптимизированные)
portfolio:
  initial_capital: 5000000    # 5 миллионов рублей
  max_risk_per_trade: 0.025   # 2.5% риска на сделку
  max_portfolio_risk: 0.12    # 12% максимальный риск портфеля
  update_interval: 300        # Обновление каждые 5 минут
  rebalance_threshold: 0.04   # Ребалансировка при 4% отклонении

# Настройки логирования (оптимизированные)
logging:
  level: INFO
  file: logs/advanced_system.log
  max_size: 50 MB
  retention: 30 days
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"

# Настройки уведомлений (расширенные)
notifications:
  enabled: true
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "your_email@gmail.com"
    password: "your_app_password"
    to_email: "your_email@gmail.com"
  
  telegram:
    bot_token: "your_telegram_bot_token"
    chat_id: "your_chat_id"

# Настройки мониторинга (расширенные)
monitoring:
  enabled: true
  web_interface:
    enabled: true
    host: "0.0.0.0"           # Доступ извне
    port: 8080
  
  metrics:
    enabled: true
    export_interval: 60       # Экспорт метрик каждую минуту
